name = "bald-eagle-proxy"
compatibility_date = "2024-01-01"

# Cloudflare Pages設定
pages_build_output_dir = "public"
node_compat = true

# 環境変数
[vars]
NODE_ENV = "production"
ENVIRONMENT = "cloudflare-pages"

# KV Namespace (セッション管理用)
[[kv_namespaces]]
binding = "SESSIONS"
id = "your-kv-namespace-id"

# Durable Objects (将来の拡張用)
# [[durable_objects.bindings]]
# name = "PROXY_SESSIONS"
# class_name = "ProxySession"
